/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './api/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design token palette (Material Design 3 derived)
        'surface': '#fbf8ff',
        'surface-dim': '#dad9e4',
        'surface-bright': '#fbf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f2fe',
        'surface-container': '#eeecf8',
        'surface-container-high': '#e9e7f2',
        'surface-container-highest': '#e3e1ed',
        'on-surface': '#1a1b23',
        'on-surface-variant': '#454654',
        'inverse-surface': '#2f3038',
        'inverse-on-surface': '#f1effb',
        'outline': '#757686',
        'outline-variant': '#c5c5d7',
        'surface-tint': '#3b4ed6',
        'primary': '#384cd3',
        'on-primary': '#ffffff',
        'primary-container': '#5366ed',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#bcc2ff',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bcc2ff',
        'on-primary-fixed': '#000c61',
        'on-primary-fixed-variant': '#1c32be',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'on-secondary-container': '#656464',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        'tertiary': '#914800',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b65c00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fbf8ff',
        'on-background': '#1a1b23',
        'surface-variant': '#e3e1ed',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'element_stack': '16px',
        'container_padding': '32px',
        'inline_padding': '12px',
        'card_gap': '24px',
        'sidebar_width': '64px',
      },
      fontFamily: {
        'geist': ['Geist', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-stat': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-stat': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(0, 0, 0, 0.05)',
        'card-hover': '0px 8px 30px rgba(0, 0, 0, 0.08)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
};
